# params.yaml

split:
  input_path: D:/YANER/MII/LB1/data/insurance.csv
  output_dir: D:/YANER/MII/LB1/data
  test_size: 0.4
  random_state: 42

decision_tree:
  max_depth: 5
  min_samples_split: 2

catboost:
  iterations: 1000
  depth: 6
  learning_rate: 0.1
  random_seed: 42
  verbose: False

xgboost:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42

mlp:
  hidden_layer_sizes: [100, 50]
  activation: relu
  solver: adam
  learning_rate_init: 0.001
  max_iter: 200
  val_size: 0.2
  random_state: 42

linear_regression:
  fit_intercept: true
  copy_X: true
  n_jobs: 1